name: Deploy to Amazon ECS

on:
 push:
  branches:
   - main

jobs:
 deploy:
  name: Deploy
  runs-on: ubuntu-latest
  environment: production

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
      
    - name: Build, tag and push image to Amazon ECR
       id: build-image
       env:
        IMAGE_TAG: ${{ github.sha }}
       run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u9m1e6h1
        docker build -t helloworldrepsitory:$IMAGE_TAG .
        docker tag helloworldrepository:latest public.ecr.aws/u9m1e6h1/helloworldrepository:$IMAGE_TAG
        docker push public.ecr.aws/u9m1e6h1/helloworldrepository:$IMAGE_TAG